-- 테스트용 H2 테이블 (운영 정의: sql/shop_schema.sql)
CREATE TABLE IF NOT EXISTS MEMBER (
    MEMBER_ID     BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EMAIL         VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(100) NULL,
    NAME          VARCHAR(50)  NOT NULL,
    GOOGLE_ID     VARCHAR(50)  NULL UNIQUE,
    CREATED_AT    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BANNER (
    BANNER_ID  INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE      VARCHAR(60)  NOT NULL,
    SUBTITLE   VARCHAR(200) NULL,
    LINK_URL   VARCHAR(200) NULL,
    LINK_TEXT  VARCHAR(30)  NULL,
    SORT_ORDER INT          NOT NULL DEFAULT 0,
    START_AT   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    END_AT     DATETIME     NULL,
    CREATED_AT DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
