-- 테스트용 H2 테이블 (운영 정의: sql/shop_schema.sql)
CREATE TABLE IF NOT EXISTS MEMBER (
    MEMBER_ID     BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EMAIL         VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(100) NULL,
    NAME          VARCHAR(50)  NOT NULL,
    GOOGLE_ID     VARCHAR(50)  NULL UNIQUE,
    CREATED_AT    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BANNER (
    BANNER_ID  INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE      VARCHAR(60)  NOT NULL,
    SUBTITLE   VARCHAR(200) NULL,
    LINK_URL   VARCHAR(200) NULL,
    LINK_TEXT  VARCHAR(30)  NULL,
    SORT_ORDER INT          NOT NULL DEFAULT 0,
    START_AT   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    END_AT     DATETIME     NULL,
    CREATED_AT DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PRODUCT (
    ITEM_CODE   VARCHAR(20)  NOT NULL PRIMARY KEY,
    ITEM_NAME   VARCHAR(50)  NOT NULL,
    UNIT_PRICE  INT          NOT NULL,
    DESCRIPTION VARCHAR(500) NULL,
    ON_SALE     TINYINT      NOT NULL DEFAULT 1,
    CREATED_AT  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS POS_SALES_DETAIL (
    RECEIPT_NO  VARCHAR(20) NOT NULL PRIMARY KEY,
    SALE_DATE   VARCHAR(8)  NOT NULL,
    ITEM_CODE   VARCHAR(20) NOT NULL,
    ITEM_NAME   VARCHAR(50) NOT NULL,
    UNIT_PRICE  INT         NOT NULL,
    QUANTITY    INT         NOT NULL,
    TOTAL_PRICE INT         NOT NULL,
    SALE_TIME   DATETIME(4) NOT NULL DEFAULT CURRENT_TIMESTAMP(4)
);

CREATE TABLE IF NOT EXISTS PAYMENT_ORDER (
    ORDER_ID    VARCHAR(20)  NOT NULL PRIMARY KEY,
    MEMBER_ID   BIGINT       NOT NULL,
    ORDER_NAME  VARCHAR(100) NOT NULL,
    AMOUNT      INT          NOT NULL,
    STATUS      VARCHAR(10)  NOT NULL DEFAULT 'READY',
    PAYMENT_KEY VARCHAR(200) NULL,
    METHOD      VARCHAR(20)  NULL,
    APPROVED_AT DATETIME     NULL,
    FAIL_REASON VARCHAR(200) NULL,
    CREATED_AT  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PAYMENT_ORDER_ITEM (
    ORDER_ID   VARCHAR(20) NOT NULL,
    LINE_NO    INT         NOT NULL,
    ITEM_CODE  VARCHAR(20) NOT NULL,
    ITEM_NAME  VARCHAR(50) NOT NULL,
    UNIT_PRICE INT         NOT NULL,
    QUANTITY   INT         NOT NULL,
    PRIMARY KEY (ORDER_ID, LINE_NO)
);
